title: IdeaSound Productions. The official site of Craig Johnson Consulting.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7496392566245049
  brandStrength: 0.2630395754240453
  lightness: 0.6030636711511761
  brandColors:
    - '#FFFFFF'
    - '#805C4C'
    - '#43392F'
    - '#FC9066'
    - '#A4D1FF'
  rhythmicContrast: 0.2263645341154188
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: IdeaSound
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4967777
layout_spectrum: 0.1318685128353536
