name: IdeaSound
favicon: null
layout_spectrum: 0.1318685128353536
typography_spectrum: 0.8517618430778384
title: IdeaSound Productions. The official site of Craig Johnson Consulting.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#63a0dc'
    - '#f9f9f9'
    - '#545758'
    - '#d3d3d3'
    - '#68ab35'
  brandStrength: 0.2630395754240453
  lightness: 0.6030636711511761
  saturation: 0.7496392566245049
  rhythmicContrast: 0.2263645341154188
purpose: []
